### ISSUE TITLE
Enable CI

### ISSUE THREAD

**Issue by gsomix** [ciwik/CorrelationService#11]
- https://www.appveyor.com

Both Win and Linux machines.
https://www.appveyor.com/docs/getting-started-with-appveyor-for-linux/

- https://travis-ci.org/

**Comment by ciwik** [comment]
CI by travis-ci was enabled. Look at afce892 and 547ff43 commits.

**Comment by gsomix** [comment]
I don't see any build and test logs. It seems your `.travis.yml` is wrong.
https://travis-ci.org/ciwik/CorrelationService/builds/366422454

Please also enable Appveyor CI.
